services:
  backend:
    build:
      context: ../backend/memciko-exercise
    container_name: memciko-backend
    ports:
      - "8080:8080"
  backend-tests:
    image: maven:3.9.9-eclipse-temurin-23
    working_dir: /app
    volumes:
      - ../backend/memciko-exercise:/app
    command: mvn test


  frontend:
    build:
      context: ../frontend/memciko-client
    container_name: memciko-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend